version: '1.0'
services:
    app:
        build:
            context:  .
        volumes:
              - .:/scubyt
        ports:
            - 3000:3000
        image: app:react
        container_name: react_container
        command: npm start